name = "FlightEDA"
uuid = "2f2f1c9e-4a7a-4a80-9c6e-0f3a83376fd2"
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
Widgets = "cc8bc4a8-27d6-5769-a93b-9d913e69aa62"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Blink = "0.12.9"
IJulia = "1.33.0"
Interact = "0.10.5"
WebIO = "0.8.21"
Widgets = "0.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
